### PR TITLE
Use the local theme as a requirement

### PR DESCRIPTION
**Pull request by daniellimws**
Try to fix the build error that occurs in #2

Edit: Great! The fix works!

### CODE REVIEW

**Comment by daniellimws** [comment]
@mithro ping

**Comment by mithro** [comment]
This doesn't seem to use the local theme as a requirement? I would expect the `docs/requirements.txt` would be adding the theme?

**Comment by daniellimws** [comment]
Oh right. I applied the changes in #3 to this branch (renaming `sphinx_material` to `sphinx_symbiflow_theme`

**Comment by daniellimws** [comment]
Apparently `docs/requirements.txt` doesn't need to contain the theme because readthedocs will automatically install our theme. I referred to the old theme and it also didn't need to have it in requirements.txt.

Checkout the preview. It's our theme now.

**Comment by mithro** [comment]
I guess this LGTM, I wonder if we can reduce the change delta to upstream however?

**Comment by daniellimws** [comment]
What do you mean?

**Pull request merged**
