### PR TITLE
Fix wrong color of theme on small screens

### PR DESCRIPTION
**Pull request by rw1nkler**
On small screens the color changes to the default rtd blue

### CODE REVIEW

**Comment by mithro** [comment]
Would be good to add an example screen shot of before / after.

**Comment by mgielda** [comment]
Saw that with my own eyes ;) indeed does happen in small resolutions
Screenshot from 2019-08-28 13-14-50

**Comment by rw1nkler** [comment]
Before:
Screenshot from 2019-08-28 13-12-56

After:
Screenshot from 2019-08-28 13-15-44

**Comment by mgielda** [comment]
I say we merge.

**Comment by mithro** [comment]
LGTM!

**Pull request merged**
