### PR TITLE
Importing SymbiFlow theme's extra features

### PR DESCRIPTION
**Pull request by mithro**
These are;
 - [x] "click-to-copy" code blocks
 - [x] Show all sidebars by default
 - [x] Extra symbiflow header links
 - [x] Extra symbiflow footer links
 - [x] Custom urls
 - [x] Default color is deep-purple

### CODE REVIEW

**Review by daniellimws — APPROVED** [review]

**Comment by daniellimws** [comment]
@mithro I haven't changed the part of `Created using Sphinx 3.3.0. and Material for Sphinx` to link to this repo yet. Will wait til this is merged.

image

**Comment by daniellimws** [comment]
Ok nevermind I just changed the link here

**Comment by mithro** [comment]
Any idea why the readthedocs builder isn't showing the changes?

**Comment by mithro** [comment]
I think we need the following,
```patch
tansell@tansell-glapstation:~/github/SymbiFlow/sphinx_symbiflow_theme$ git diff HEAD~1
diff --git a/docs/requirements.txt b/docs/requirements.txt
index 3c83835..dbbe020 100644
--- a/docs/requirements.txt
+++ b/docs/requirements.txt
@@ -1,4 +1,3 @@
-sphinx_material
 numpy>=1.16
 pandas
 matplotlib
@@ -11,3 +10,4 @@ ipykernel
 recommonmark
 sphinx_markdown_tables
 sphinx-copybutton
+-e ../
```

**Comment by daniellimws** [comment]
I believe we need to change `sphinx_material` to `sphinx_symbiflow_theme`. Can you publish this to pip?

**Pull request merged**
